# Site settings
title: Schuyler

avatar: https://github.com/schuyler-smith.png
page_icon: "/imgs/icon.png"

name: Schuyler D. Smith
description: Ph.D. Student - Bioinformatics and Computational Biology

#media list items
email: sdsmith@iastate.edu
cv: https://schuyler-smith.github.io/pages/Smith_Schuyler_CV.pdf
google_scholar: https://scholar.google.com/citations?user=fTKo_RgAAAAJ&hl=en&oi=sra
orcid_id: 0000-0001-5720-5611
github_username:  schuyler-smith
instagram_username:  schuylerds

#navigation bar links
page_1: about
page_2: 
page_3: phylosmith
page_4: 
page_5: 
page_6: photos

