# Site settings
title: Schuyler

avatar: https://github.com/schuyler-smith.png
page_icon: "/imgs/icon.png"

name: Schuyler D. Smith
description: Ph.D. Student - Bioinformatics and Computational Biology

github_username:  schuyler-smith
instagram_username:  schuylerds
email: sdsmith@iastate.edu
google_scholar: https://scholar.google.com/citations?user=fTKo_RgAAAAJ&hl=en&oi=sra
cv: https://drive.google.com/file/d/1L9kKqpT60JyrhBv6vr0f1qjS--IQVL2b/view
#twitter_username: 
#steam_username: 

#navigation bar links
page_1: about
page_2: photos
page_3: 
page_4: 
page_5: 
page_6: 


